### ISSUE TITLE
uploadData seems to open new TCP connections by not re-using the HTTPClients

### ISSUE THREAD

**Issue by alexzautke** [mcuf-idim/fhir-benchmark#2]
Hi @martinhinze,

after working through the issues with the invalid references, we now stumble into the issue that the uploadData function doesn't seem to recycle the HTTP clients. That results on our VM in the case that around 32 thousand TCP connections are being kept open. After reaching the this maximum of Docker, the script fails to connect to our FHIR server. We are currently looking into if we can somehow adjust this. We keep getting the error:

Error sending PUT request: Put "http://firelyserver:4080/Immunization/ab65a433-334f-8de3-fb2c-1adb436f3d97": dial tcp 172.18.0.2:4080: connect: cannot assign requested address

This again influences the number of false-positive errors in our statistic.

Any help on short notice would be appreciated. Maybe you could see to build in a quick re-try mechanism.

Thanks!

**Comment by martinhinze** [comment]
Hello @alexzautke,

Thank you for bringing this issue to our attention. We haven’t encountered this problem on our side, so I’m unable to reliably reproduce it. However, I’ve made some changes that should address the issue.

I created a new branch, [enhance-connection-management](https://github.com/mcuf-idim/fhir-benchmark/tree/enhance-connection-management), where I slightly rewrote the uploadData() function to ensure that TCP connections are properly closed and to limit the number of concurrent connections to 256.

Please clone the repo with the new branch, test the changes, and let me know if this resolves the issue on your end.

**Comment by alexzautke** [comment]
@martinhinze We managed to get this up and running in the mean time. Turns out that the 32000 is a strict limit if you use the Docker network when routing between the Docker image for the test runner and a docker image for the FHIR server. If you configure them both to use the host network, it works with more open connections.

We have now a successful test run and are able to submit the requested numbers. Thank you so much for your help so far.

**Comment by martinhinze** [comment]
@alexzautke I’m glad to hear you got the benchmark working, and I really appreciate your patience. The issues you raised have been invaluable in helping us address problems that could have become more severe as we scale up with larger data sets and higher thread counts.
